### ISSUE TITLE
how to get the startDate and endDate from onConfirm function?

### ISSUE THREAD

**Issue by wendy-peiwen** [pohsiu/react-native-date-ranges#10]
customButtonOnPress = () => {
    console.log('customButton');
    this.picker.onConfirm();
}

from this function, how to get startDate and endDate?

**Comment by pohsiu** [comment]
Good Question, I would take a look of it

**Comment by pohsiu** [comment]
@wendy-peiwen you can try the latest version of customButton.
I've modified the way of using customButton, check it first of readme

**Comment by pohsiu** [comment]
actually, in original you can access the onConfirm with ref. But I change it anyway.

**Comment by IyiolaOwabumowa** [comment]
Hi.. can you kindly show me the code that displays the date object?
