### ISSUE TITLE
Latest commit 1e11389 hasn't been published to npm

### ISSUE THREAD

**Issue by Guiaki** [pohsiu/react-native-date-ranges#12]
The latest commit 1e1138948d583711dd5ff7ae363e0c4f29e7f6de is not being downloaded through yarn/npm and the release at [Releases Page](https://github.com/pohsiu/react-native-date-ranges/releases) is not with the last commit:
`{this.renderButton()}`

**Comment by pohsiu** [comment]
Sorry, I just published.
