### ISSUE TITLE
How to add default startDate and endDate

### ISSUE THREAD

**Issue by Shubham-Sinha** [pohsiu/react-native-date-ranges#14]
There should be any prop to add start and end date?

**Comment by pohsiu** [comment]
currently can't achieve it, I will figure it out.

**Comment by marketiweb** [comment]
<DatePicker onConfirm={({startDate,endDate})=>{this.state.startDate=startDate; this.state.endDate=endDate; }} />

Remember set states first:

state = {
        startDate: '',
        endDate: ''
    }

**Comment by pohsiu** [comment]
@Shubham-Sinha for now, u only can decide block day before today or day after today.
Do you mean set a range that you only can select from, right?

**Comment by pohsiu** [comment]
@Shubham-Sinha If true, you can try the branch [specifyRanges ](https://github.com/pohsiu/react-native-date-ranges/tree/specifyRange)
