### ISSUE TITLE
Retrieve startDate and endDate from CustomButton?

### ISSUE THREAD

**Issue by majidalik** [pohsiu/react-native-date-ranges#16]
Can you please share the lines of code how can i retrieve startDate, endDate?

HERE IS MY CODE
----------------------------------
    <DatePicker
         centerAlign 
          allowFontScaling={false} 
          placeholder={'Apr 27, 2018 → Jul 10, 2018'}
          mode={'range'}
          markText="Select date | Select dates"
          customButton={this.customButton}
        />

------------------------------------------------------------------------------
  customButton = (onConfirm) => (
    <Button
      onPress={onConfirm}
      style={{ container: { width: '80%', marginHorizontal: '3%' }, text: { fontSize: 20 } }}
      title="Confirm"
    />

**Comment by majidalik** [comment]
I resolved myself.
 onConfirm = value => {
    alert("Start date "+ value.startDate +" "+ "End date "+ value.endDate)
  };

**Comment by IyiolaOwabumowa** [comment]
I still didn't get ot.. start and end were undefined
