### ISSUE TITLE
How to get the Start and End Date Object

### ISSUE THREAD

**Issue by IyiolaOwabumowa** [pohsiu/react-native-date-ranges#23]
I have ZERO CLUE

I tried using this:

  `
  onConfirm = value => {
    alert("Start date " + value.startDate + " " + "End date " + value.endDate);
  };
`

It didn't work

**Comment by m0zee** [comment]
`onConfirm={(data)=>{console.log(data); return data;}}`
it will return `{startDate: "2019-12-18", endDate: "2019-12-25"}`
