### ISSUE TITLE
Default text is in Chinese

### ISSUE THREAD

**Issue by adriantache** [pohsiu/react-native-date-ranges#4]
I think it would make sense to add a prop to control those two text fields

EDIT: After looking at the source code, there is a hidden prop called "markText" which controls the top left text and another one called "ButtonText" which controls the "submit" text. I recommend adding these to the readme

**Comment by pohsiu** [comment]
sure, I will take care of that

**Comment by pohsiu** [comment]
@adriantache readme has been modified
