### ISSUE TITLE
No way to exit picker without choosing dates

### ISSUE THREAD

**Issue by adriantache** [pohsiu/react-native-date-ranges#5]
Sometimes a user clicks on the date picker by accident and there is no way to close the modal, either with an X or by using the back button on Android

**Comment by pohsiu** [comment]
Actually, I want to keep it simple. 
Adding icon might increase dependency like react-native-icon-vectors ... etc .
For now, I would recommend you fork the repo and custom it.

**Comment by adriantache** [comment]
I understand what you mean, but you could simply add an [X] and a hook to the back button. Alternatively, you could simply add a font arrow to the Select Dates font and hook into that.

But you're right, if I have time I'll just make a fork.
